name: Edit PR
on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR#"
        required: true
jobs:
  edit-pr:
    name: Editing PR
    runs-on: ubuntu-latest
    env:
      # Token required to submit comments on failed PRs
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: edit pr
      run: |
        echo "BETTER README" > README.md
        git commit -am "make an even better README"
        git push
        
